### ISSUE TITLE
detection lossについて

### ISSUE THREAD

**Issue by asao-kanta** [jjjkkkjjj/pytorch.dl#12]
こんばんわ、先日も質問した者です。
無事学習を進めることができ、公開されている重みを使用して転移学習をしております。

しかし、手元の300枚のデータを学習させたところ下のようなlossになりました。
同じような画像のデータセットで学習させ、trainデータセットと同じようなtest画像に推論をさせたいので、正直過学習してもいいのですが、検出精度だけ非常に悪いです。

使用しているコードは公開されているgithubのデータセットと保存のパスだけ変更して使用しております。
これはやはりデータセットの作成方法に起因しているのでしょうか。

作成したデータセットの矩形はそこまでタイトにしておりません。

データのすべてのxmlファイルについて画像に矩形を表示して確認しましたがきちんと文字をとっており、左上スタートになっておりました。

![fots_learning-curve_e-10](https://user-images.githubusercontent.com/70710821/177199686-5fb9ba2f-22cf-4d11-81d2-97a1bd89a0c1.png)

**Comment by jjjkkkjjj** [comment]
これはちょっとおかしいですね。
recognition lossがほぼ0なのが気になります。

お聞きしたい事は、以下の通りです。

- 教師データのラベルは何個か
- lossのコンソール出力は初めからrecognition lossが0か

チェックポイントとしては、以下の通りです。

- 入力画像は標準化したか
- 教師データのラベルを適切にワンホットエンコードしているか
- [こちら](https://github.com/jjjkkkjjj/pytorch.dl/blob/master/demo/fots/debug_dataset.ipynb)と同じように、適切にボックスと文字が表示されるか
- 学習は[こちら](https://github.com/jjjkkkjjj/pytorch.dl/blob/master/demo/fots/train_ICDAR2013%2B15.ipynb)のコードを参考にしたか

もしお時間有れば、上記ご確認頂けますと幸いです。

**Comment by jjjkkkjjj** [comment]
データセットの作成方法で何か抜け漏れがあるような気がします。

**Comment by asao-kanta** [comment]
私も自分のデータセット作成が悪いと思ってます。
教師データラベルは100以上あります。
recognition loss は1epoc目、1iteration目で0.6です。

`Training... Epoch: 0, Iter: 1,   3%[1/37]       total: 9.865605 detection: 9.237144 recognition: 0.628461`

**Comment by asao-kanta** [comment]
標準化はされていると思います。
```
transform = transforms.Compose(
        [transforms.Resize((640, 640)),
         transforms.ToTensor(),
         transforms.Normalize(rgb_means=(0.485, 0.456, 0.406), rgb_stds=(0.229, 0.224, 0.225))]
    )
```
こちらをそのまま使用しております。
学習に使用したコードは[こちら](https://github.com/jjjkkkjjj/pytorch.dl/blob/master/debug/fots/train.py)です。

**Comment by asao-kanta** [comment]
ボックスと文字は昨日確認してちゃんと入っていたと思いますが今一度確認します。
ワンホットエンコードについても確認します。

お手数おかけして申し訳ありません。

**Comment by asao-kanta** [comment]
> 私も自分のデータセット作成が悪いと思ってます。 教師データラベルは100以上あります。

画像データ一枚につきユニークな文字列が一つずつあるので400枚データに対して教師データラベルは500くらいあります

**Comment by jjjkkkjjj** [comment]
教師データのラベルが多いので、`FotsLoss`のハイパーパラメータである`recog_coef`の値を大きくしてみるのも良いかもしれません。

**Comment by jjjkkkjjj** [comment]
いえ、何とか解決できればと思います。

**Comment by asao-kanta** [comment]
ありがとうございます。
ボックスと文字は適切に入っております。
エンコードも入っておりました。
`recog_coef`の値はいじって精度確認をしてみます。

detectionについてなのですが、学習した後が格段に精度が下がってしまっていて、何か良くない学習法をしているのでしょうか。

**Comment by asao-kanta** [comment]
アノテーションがおそらくダメだと思うのですが、どこが悪いかわからくて。。
どこかでログを出力したらわかるのでしょうか。

**Comment by asao-kanta** [comment]
[こちら](https://github.com/jjjkkkjjj/pytorch.dl/blob/master/demo/fots/train_ICDAR2013%2B15.ipynb)のコードを参考に学習したところdetection lossが正常になった気がするのでこのまま学習を進めてみます。
原因がわからないので気持ちが悪いですが、、

`Training... Epoch: 1, Iter: 58,	 57%[21/37]	total: 0.502197 detection: 0.471905 recognition: 0.030293`

**Comment by asao-kanta** [comment]
このようになりました。
学習が進んでもlossがそこまで変わらないのが気になりますが、パラメータを変えてやってみようと思います

![fots_learning-curve_e-10](https://user-images.githubusercontent.com/70710821/178111573-396b6fa0-cec4-47ab-9a77-39dd4aa70230.png)

**Comment by jjjkkkjjj** [comment]
Lossのグラフはもっと乱高下すると思うので、やっぱりおかしい気がします。

> どこかでログを出力したらわかるのでしょうか。

原因はいろいろ考えられますが、

- CRNNに渡す画像のサイズは適切（ある程度大きいか）をログ出力してみる
- CRNNの予測が全部0になってないかをログ出力してみる
- ついでに、既存のアルファベットを出力するモデルになってないかも気になるので、モデルの出力のshapeも出力してみる

を確認することは可能でしょうか？

**Comment by jjjkkkjjj** [comment]
> このようになりました。

ちなみに、学習したデータセットに対しては正しく予測できていますでしょうか？

**Comment by asao-kanta** [comment]
> ちなみに、学習したデータセットに対しては正しく予測できていますでしょうか？

予測の上位10個を表示するようにしていますが、必ず3個目以内には正解が来ているので認識精度は悪くないと思ってますが、検出のほうがあまりよくなっていない印象です。

多少ばらつきはありますが、基本的には下の画像のように5つの矩形をとりたいのですが、よく右上の矩形が取れないです。
trainデータとtestデータでとりたい矩形が同じなのでもっと精度が出ると期待しているのですが。。

![S__2113538](https://user-images.githubusercontent.com/70710821/178125796-ee162e7f-36a4-411c-b9eb-d481b6ccaa55.jpg)

**Comment by asao-kanta** [comment]
> CRNNに渡す画像のサイズは適切（ある程度大きいか）をログ出力してみる

画像サイズは以下であってますかね。
```
print(rotated_features[b].shape)
```
```
torch.Size([5, 32, 8, 21])
torch.Size([1, 32, 8, 18])
torch.Size([5, 32, 8, 32])
torch.Size([5, 32, 8, 32])
torch.Size([5, 32, 8, 23])
torch.Size([1, 32, 8, 13])
torch.Size([3, 32, 8, 32])
torch.Size([1, 32, 8, 20])
```

> CRNNの予測が全部0になってないかをログ出力してみる

ちゃんと値が入っておりました。

> ついでに、既存のアルファベットを出力するモデルになってないかも気になるので、モデルの出力のshapeも出力してみる

こちらがよくわかってないのですが、もう少しかみ砕いた説明いただけますか？

お手数おかけします

**Comment by jjjkkkjjj** [comment]
モデルの出力というのは、CRNNの出力のshapeになります。

[ここ](https://github.com/jjjkkkjjj/pytorch.dl/blob/d82aa1191c14f328c62de85e391ac6fa1b4c7ee3/dl/loss/fots.py#L221)の部分の
`predicts[b], targets[b], predict_lengths[b], target_lengths[b]`のshapeのことになります。

**Comment by jjjkkkjjj** [comment]
Detectionはぱっと見問題無さそうです

**Comment by asao-kanta** [comment]
```
len(predicts)=8

predicts
torch.Size([22, 5, 69])

targets
torch.Size([5, 6])

predict_lengths
torch.Size([5])

target_lengths
torch.Size([5])
```
このような出力になってます

**Comment by jjjkkkjjj** [comment]
それらの値は見れますか？

認識したい文字は69文字ですか？

**Comment by asao-kanta** [comment]
はい、認識したい文字は数字とローマ字の36文字です。

google colabの容量がなくなったので少々お待ちいただけますか。

**Comment by asao-kanta** [comment]
jupyter notebookを立ち上げて同様のコード実行したのですが、またlossが最初と同じようになってしまったのでどこがダメか確認しています

**Comment by jjjkkkjjj** [comment]
もし、icdarのデータセットで同様の症状だった場合は、こちらのバグになります…

**Comment by asao-kanta** [comment]
確認してみますが、多分私のほうに問題があると思います。
さっきはできていましたし、、
また明日google colabのメモリが復活したらもう一度それも確認します。

あとはデータ量の問題なのでしょうか。

**Comment by jjjkkkjjj** [comment]
> 認識したい文字は数字とローマ字の36文字

見逃していましたが、36文字で有れば、`predicts`のshape（順番に、可変長の幅、バッチ数（ここでは一枚の画像の文字領域の数）、分類したい文字数=69）が69なのはおかしい気がします。

`TargetTransforms`とモデルの生成部分のコードら共有できますか？

**Comment by asao-kanta** [comment]
確かに、気にせずコードそのまま使用しておりました。

```
augmentation = augmentations.Compose([
        augmentations.RandomLongerResize(smin=640, smax=2560),
        augmentations.RandomRotate(fill_rgb=(103.939, 116,779, 123.68), amin=-10, amax=10, same=True),
        augmentations.RandomScaleV(smin=0.8, smax=1.2, keep_aspect=True),
        augmentations.RandomSimpleCrop()
    ])

ignore = target_transforms.Ignore(strange=True, difficult=True)

transform = transforms.Compose(
    [transforms.Resize((640, 640)),
     transforms.ToTensor(),
     transforms.Normalize(rgb_means=(0.485, 0.456, 0.406), rgb_stds=(0.229, 0.224, 0.225))]
)
target_transform = target_transforms.Compose(
    [target_transforms.Text2Number(class_labels=datasets.SynthText_char_labels_without_upper_blank, ignore_nolabel=False),
     target_transforms.ToTensor(textTensor=True)]
)


train_dataset = datasets.SynthTextDetectionDataset(ignore=ignore, transform=transform, target_transform=target_transform, augmentation=augmentation,
                                                            onlyAlphaNumeric=False)

train_loader = DataLoader(train_dataset,
                          batch_size=8,
                          shuffle=True,
                          collate_fn=utils.batch_ind_fn,
                          num_workers=4,
                          pin_memory=True)

model = FOTSRes50(chars=datasets.SynthText_char_labels_without_upper_blank, input_shape=(None, None, 3), feature_height=8).cuda()
model.load_weights('./sample_weights/jjjsample.pth')
```

**Comment by asao-kanta** [comment]
使用しているコードはpath以外はgithubのそのまま使用しております

**Comment by jjjkkkjjj** [comment]
これまたぱっと見大丈夫そうな気がします…

確認事項多くて恐縮ですが、もし可能なら

https://github.com/jjjkkkjjj/pytorch.dl/tree/master/demo/fots
のdebug関係でご自身のデータセットが適切に表示されるか確認できますか？

**Comment by asao-kanta** [comment]
debug_datasetを試しましたところ正常に表示されました

**Comment by asao-kanta** [comment]
detection lossがまた最初と同じようになって、精度が格段に落ちてしまいました、、
うーん、原因がわかりません

![image](https://user-images.githubusercontent.com/70710821/178144667-f6246011-8120-406a-950e-d52150838adf.png)

**Comment by jjjkkkjjj** [comment]
上記の結果はicdarデータセットのものですか？

**Comment by asao-kanta** [comment]
いいえ、独自のデータセットです。
icdarについては今中身を確認して学習用を作成してます。
紛らわしくてすみません

**Comment by asao-kanta** [comment]
gpuのメモリの問題ですごく時間がかかりました、すみません

![fots_learning-curve_e-50](https://user-images.githubusercontent.com/70710821/178153701-8bc9ebc0-d173-4417-9d1b-f5dfd6de7f44.png)

icdar datasetの229枚の画像に対し50epoc回しました。
自分のデータセットと同じような傾向にあります。
作ったデータセットは[こちら](https://drive.google.com/drive/folders/1wRqCi0558nbWWw1oD3lJ4pGKjLm31mEn?usp=sharing)に置いておきますのでもしよかったらご確認いただきたいです。

**Comment by jjjkkkjjj** [comment]
ありがとうございます。
これはおかしいですね…
実を言うと、何回かリファクタリングをしているので、もしかしたらそれが原因でこちらにバグが生じているのかもしれません。
もしそうだとしたら、本当に申し訳ないです。確認のため、少しお時間を頂けますでしょうか？確認してみます。

**Comment by jjjkkkjjj** [comment]
ちなみに私の環境でのICDAの学習は問題なさそうでした．

```
Training... Epoch: 0, Iter: 40,	 20%[40/205]	total: 2.588089 detection: 1.281928 recognition: 1.306161 	Iter time: 0.6093
```

**Comment by asao-kanta** [comment]
いえいえ、お手数おかけします。

**Comment by asao-kanta** [comment]
本当ですね、pathがおかしいのかな。
もしよかったらdatasetsのファイル構造と、使用したコードそのままいただけたりしますか？？

**Comment by asao-kanta** [comment]
@jjjkkkjjj 
コード頂くのは難しいでしょうか？

**Comment by jjjkkkjjj** [comment]
> ちなみに私の環境でのICDAの学習は問題なさそうでした．
> 
> ```
> Training... Epoch: 0, Iter: 40,	 20%[40/205]	total: 2.588089 detection: 1.281928 recognition: 1.306161 	Iter time: 0.6093
> ```

コードはこれと同じものを使っています．
https://github.com/jjjkkkjjj/pytorch.dl/blob/master/demo/fots/train_ICDAR2013%2B15.ipynb

ファイル構造は`~/data/text/`以下はこちらのようになっています．

`datasets.ICDAR2015TextDataset`クラスは，デフォルトで`~/data/text/ICDAR2015`を探すようになっています．

```
text/
├── Born-Digital-Images
│   ├── Annotations
│   ├── ch1_training_localization_transcription_gt.zip
│   ├── Challenge1_Training_Task12_Images.zip
│   └── Images
├── Focused-Scene-Text
│   ├── Annotations
│   ├── ch2_training_images.zip
│   ├── ch2_training_localization_transcription_gt.zip
│   └── Images
├── ICDAR2015
│   ├── Annotations
│   └── Images
├── ICDAR2017MLT
│   ├── Annotations
│   └── Images
├── ICDAR2017MLT-val
│   ├── Annotations
│   └── Images
└── SynthText
    ├── Annotations
    ├── license.txt
    └── SynthText

```

**Comment by jjjkkkjjj** [comment]
転移学習はしたことがないので，今手元にコードがないです．．．
平日はなかなか時間が取れないので，もうしばらくお待ちいただけますと幸いです．

**Comment by asao-kanta** [comment]
そうですよね、無理言って住みません。
ファイル構造いただけただけでありがたいです！！
明日自分のもの比較、確認してみます！
ありがとうございます

**Comment by asao-kanta** [comment]
[fots/base.py](https://github.com/jjjkkkjjj/pytorch.dl/blob/master/dl/models/fots/base.py)で以下のコードを使用し、画像と予想矩形、正解矩形が入っていることを確認しました。
矩形の入っている順番の確認のため、rectangleではなくlineで描画しています。

```
# ここが149行目
if self.training:
            # create pos_indicator and rboxes from label
            _, _, h, w = fmaps.shape
            device = fmaps.device
            pos_indicator, true_rboxes = matching_strategy(labels, w, h, device, scale=self.shrink_scale)

            # RoI Rotate Branch
            # list(b) of Tensor, shape = (text nums, c, height=8, non-fixed width)
            true_quads = [l[:, 4:12] for l in labels]
            rotated_features = self.roi_rotate(fmaps, true_quads)

            # confirm img and true quads
            import numpy as np
            import cv2
            with torch.no_grad():
                batch_nums, _, h, w = fmaps.shape
                sample_pred_quads = torch.from_numpy(rboxes2quads_numpy(pred_rboxes.cpu().numpy()))
                sample_pred_quads = sample_pred_quads.reshape((batch_nums, -1, 8))
                sample_pred_confs = pred_confs.reshape((batch_nums, -1))
                sample_filtered_mask = sample_pred_confs > self.conf_threshold
                # nms
                ret_quads = []
                for b in range(batch_nums):
                    # p_quads: shape = (h*w, 8)
                    # p_confs: shape = (h*w,)
                    p_quads = sample_pred_quads[b][sample_filtered_mask[b]]
                    p_confs = sample_pred_confs[b][sample_filtered_mask[b]]
                    indices = locally_aware_nms(p_confs, p_quads, self.topk, self.iou_threshold, quads_iou)
                    p_quads[:, ::2] /= w
                    p_quads[:, 1::2] /= h
                    ret_quads += [p_quads[indices]]

                for b, sample_img in enumerate(x):
                    sample_img = np.array(sample_img.cpu())
                    sample_img = sample_img.transpose(1,2,0).astype(np.uint8).copy()
                    for p_quads, t_quads in zip(ret_quads[b], true_quads[b]):
                        p_quads = [int(n*640) for n in p_quads]
                        p_x1 = p_quads[0]
                        p_x2 = p_quads[2]
                        p_x3 = p_quads[4]
                        p_x4 = p_quads[6]
                        p_y1 = p_quads[1]
                        p_y2 = p_quads[3]
                        p_y3 = p_quads[5]
                        p_y4 = p_quads[7]
                        t_quads = [int(n*640) for n in t_quads]
                        t_x1 = t_quads[0]
                        t_x2 = t_quads[2]
                        t_x3 = t_quads[4]
                        t_x4 = t_quads[6]
                        t_y1 = t_quads[1]
                        t_y2 = t_quads[3]
                        t_y3 = t_quads[5]
                        t_y4 = t_quads[7]

                        cv2.line(sample_img, (int(p_x1), int(p_y1)), (int(p_x2), int(p_y2)), (255, 0, 0), thickness=2, lineType=cv2.LINE_8, shift=0)
                        cv2.line(sample_img, (int(p_x2), int(p_y2)), (int(p_x3), int(p_y3)), (255, 0, 0), thickness=2, lineType=cv2.LINE_8, shift=0)
                        cv2.line(sample_img, (int(p_x3), int(p_y3)), (int(p_x4), int(p_y4)), (255, 0, 0), thickness=2, lineType=cv2.LINE_8, shift=0)
                        cv2.line(sample_img, (int(p_x4), int(p_y4)), (int(p_x1), int(p_y1)), (255, 0, 0), thickness=2, lineType=cv2.LINE_8, shift=0)
                        cv2.line(sample_img, (int(t_x1), int(t_y1)), (int(t_x2), int(t_y2)), (0, 255, 0), thickness=2, lineType=cv2.LINE_8, shift=0)
                        cv2.line(sample_img, (int(t_x2), int(t_y2)), (int(t_x3), int(t_y3)), (0, 255, 0), thickness=2, lineType=cv2.LINE_8, shift=0)
                        cv2.line(sample_img, (int(t_x3), int(t_y3)), (int(t_x4), int(t_y4)), (0, 255, 0), thickness=2, lineType=cv2.LINE_8, shift=0)
                        cv2.line(sample_img, (int(t_x4), int(t_y4)), (int(t_x1), int(t_y1)), (0, 255, 0), thickness=2, lineType=cv2.LINE_8, shift=0)
                    ipath = 'C:/Users/kd207/pytorch.dl/confirm_img/{}_img.jpg'.format(b)
                    cv2.imwrite(ipath, sample_img)
```

出力結果
![0_img](https://user-images.githubusercontent.com/70710821/179185431-fb4606a4-3d24-4d31-93bd-db94d3a27314.jpg)



私のデータセットに対してはもう少し予想矩形が正解に近かったです。（恐らく予測が簡単な画像のため）
この時のloss結果が以下のような感じです。
`Training... Epoch: 0, Iter: 1,   0%[1/217]      total: 11.070047 detection: 10.213041 recognition: 0.857006`

学習を進めた後の同じ画像に対しての推論結果が以下の通りです。
![fots_model0](https://user-images.githubusercontent.com/70710821/179185341-4ffa2f5e-12a1-4ecf-9e82-a071bd39723f.png)

lossの結果が以下の通りです。
![fots_learning-curve_e-10](https://user-images.githubusercontent.com/70710821/179182970-31487d61-aadd-4ac7-b623-6a085d6f041a.png)

ですのでloss計算の部分を見ていただきたいです。
力不足でloss部分のデバッグができておりません。

**Comment by asao-kanta** [comment]
一枚目の出力画像については緑が正解矩形で青が予測矩形です

**Comment by jjjkkkjjj** [comment]
うーん，どう考えても学習がうまくいっていないですね．
やはり，Lossというよりはデータセットな気がするのですが．．．（手元のデータで再学習させてみます．）

本当に[ここ](https://github.com/jjjkkkjjj/pytorch.dl/tree/master/demo/fots)の`debug_**.ipynb`で正しく，データセットが出力されていますか？

以下，同様の画像で予測した結果です．

SynthTextモデル

![test-pre](https://user-images.githubusercontent.com/16914891/179285095-cbe46ddb-b23d-41c9-8c94-2ee9b4008a05.png)

ICDARで学習済みモデル（これはこれで不本意ですが）

![test-result](https://user-images.githubusercontent.com/16914891/179285105-c5783e49-5952-4070-a138-11025416527e.png)

**Comment by asao-kanta** [comment]
やっぱりdatasetsの問題ですよね。
出力結果としては以下の通りで問題ないと思っています。
![スクリーンショット (23)](https://user-images.githubusercontent.com/70710821/179317116-4e786485-98a1-4f3f-9444-083bd5092e52.png)
![スクリーンショット (24)](https://user-images.githubusercontent.com/70710821/179317123-9d382bdb-b2fa-49f5-9f17-eeef594f3d89.png)
![スクリーンショット (25)](https://user-images.githubusercontent.com/70710821/179317126-25352419-d422-452c-a217-047e2162e8bd.png)
![image](https://user-images.githubusercontent.com/70710821/179317134-5e797ec3-1bf5-4f33-83bd-b64d0656b402.png)

**Comment by asao-kanta** [comment]
どこに問題があるかがいまいちわかってなくって困っています。

**Comment by jjjkkkjjj** [comment]
学習用のコードを共有することは可能ですか？
ここでなくても、ドライブにipynbで共有でも良いです。lossに関しては、それから見てみます。

**Comment by asao-kanta** [comment]
学習用コードをそのまま共有しました。
ご確認ください。
ファイルはC://Users/(username)/pytorchdl/の位置に入れて動作しております。
自分は.pyファイルのほうを使用しておりますが、ipynbも動作すると思います。多分。。

**Comment by jjjkkkjjj** [comment]
ありがとうございます．Colabでそちらのドライブ上データに対して，実行しました．
少なくとも，Lossの乖離はないようです．

![image](https://user-images.githubusercontent.com/16914891/179334904-7205b31d-a941-4839-ad0c-07c942d83bcf.png)

**Comment by jjjkkkjjj** [comment]
ただ，ICDARのフォルダが`images`になっていたので，`Images`に変更しています．

**Comment by jjjkkkjjj** [comment]
`datasets`の生成を以下のようにすると良いかもしれません．

```python
train_dataset = datasets.ICDARTextMultiDatasetBase(
    icdar_dir=('./data/text/ICDAR2015', './data/text/Born-Digital-Images', './data/text/Focused-Scene-Text'),
    ignore=ignore, transform=transform, target_transform=target_transform, augmentation=augmentation
)
```

私が実行したJupyterはドライブにアップロードしましたので，一度そちらで試してみてください．やはり，うまくデータセットが読み込めていないのが原因だと思います．

**Comment by asao-kanta** [comment]
ありがとうございます。
こちら試して自前のデータセットに対しても実行してみます

**Comment by asao-kanta** [comment]
icdar datasetsに対しての乖離が少なくなりました

![fots_learning-curve_e-10 (1)](https://user-images.githubusercontent.com/70710821/179337339-bd59e364-ad65-49bd-8f84-0e58aa12dff4.png)

![icdar_val](https://user-images.githubusercontent.com/70710821/179337343-41ffaa57-241f-44c0-9007-85af5515007f.png)

このまま一度自前データセットに対してやってみるので一度アクセス権を削除しました

**Comment by asao-kanta** [comment]
`Training... Epoch: 1, Iter: 182,	 3%[6/176]	total: 0.364670 detection: 0.344332 recognition: 0.020339 	Iter time: 0.3154`
直ったと思います！！
こんなのに何時間も時間とらせてすみません。
付き合っていただきありがとうございました。
本当にありがとうございます

**Comment by jjjkkkjjj** [comment]
よかったです！
DeepLearning実装あるあるですね．．．
私のプログラム自体が綺麗ではないので，デバッグしづらかったのは大変申し訳ないです．

転移学習がどうなったのか気になるところなので，もし良かったら結果をご教示いただけますと幸いです．
引き続き頑張ってください！

**Comment by asao-kanta** [comment]
![fots_learning-curve_e-10 (2)](https://user-images.githubusercontent.com/70710821/179342885-99406137-ec38-4426-9b48-61a9a5ceb777.png)

推論結果は矩形がとりにくい位置があるみたいですが概ね良好だと思います。
全体的に見て8~9割検出、認識に成功していると思います！

あとはデータを増やしてやってみようと思います。

**Comment by asao-kanta** [comment]
lossの乱高下は相変わらずないですが、、、

**Comment by jjjkkkjjj** [comment]
おお〜良い感じですね。
乱高下の原因は、学習データの短形の数などにも依存しそうな気がします。
そのあたりは、lossの工夫などで抑えることが出来そうです。時間あったら、`FotsLoss`を継承して、自作してみるのもありだと思います（丸投げ）。
